included:
  - Leef
  
excluded:
  - Pods
  - Frameworks
  - Products
  - Target Support  Files
  
disabled_rules:
- trailing_whitespace
- vertical_whitespace
- line_length
  
opt_in_rules:
  - empty_count
  - file_header
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - force_unwrapping
  - sorted_imports
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message


number_separator:
  minimum_length: 5


